### ISSUE TITLE
Calculation.PercentTrue missing in the WebAPI

### ISSUE THREAD

**Issue by karlmtc** [osimloeff/PI-Web-API-Client-DotNet-Standard#5]
I don't know if you guys know about this or if it's an issue related with the web api itself. I was wondering why the PercentTrue method was removed on the WebAPI. Do you know if it will be available in the future?

**Comment by osimloeff** [comment]
Is this present on the server side?

https://techsupport.osisoft.com/Documentation/PI-Web-API/help.html

If not, please create a new thread on PI Developers Club (https://pisquare.osisoft.com/community/developers-club) since your question would not be specific related to the library. 

Regards,

Marcos

**Comment by karlmtc** [comment]
You're right, it's not. I'll request it then on the forum. Thanks.
